version: 2

models:
  - name: unique_parts
    description: the part_nums that are only used in one set
    columns:
      - name: part_num
        tests:
          - unique 

  - name: parts_per_set
    description: shows the number of parts used in a set and whether they're unique or not null
    columns:
      - name: theme_name
        tests:
          - not_null
      - name: set_name
        tests:
          - not_null
      - name: set_year
        tests:
          - not_null      